apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-camunda-bpm
  labels:
    app: spring-boot-camunda-bpm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-camunda-bpm-app
  template:
    metadata:
      labels:
        app: spring-boot-camunda-bpm-app
    spec:
      containers:
        - name: spring-boot-camunda-bpm
          image: docker.pkg.github.com/augustoximenes/spring-boot-camunda-bpm/spring-boot-camunda-bpm:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: github-spring-boot-camunda-bpm-app
