apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: spring-boot-camunda-bpm
  namespace: spring-boot-camunda-bpm
spec:
  path: /
  to:
    kind: Service
    name: spring-boot-camunda-bpm
  port:
    targetPort: 8080
