spring:
  datasource:
    url: jdbc:mysql://db:3306/camunda
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: camunda
    password: camunda
  kafka:
    consumer:
      bootstrap-servers: broker:9092
      group-id: group_id
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: broker:9092

camunda:
  bpm:
    database:
      type: mysql
    admin-user:
      id: demo
      password: demo