spring:
  datasource:
    url: jdbc:mysql://localhost:3306/camunda
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: camunda
    password: camunda
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      group-id: group-id
      auto-offset-reset: earliest

camunda:
  bpm:
    database:
      type: mysql
    admin-user:
      id: demo
      password: demo