apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: spring
  name: spring
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: spring
    spec:
      containers:
      - image: spring-boot-camunda-bpm/my-project:latest
        name: spring
        ports:
        - containerPort: 8080
        resources: {}
      hostname: spring
      restartPolicy: Always
status: {}
